blank_issues_enabled: false
contact_links:
  - name: Ask the community
    url: https://github.com/dkyung213team/inov/discussions/new
    about: Ask and discuss questions with other community members.
